### PR TITLE
Add order dice

### PR DESCRIPTION
**Pull request by LeadAddict**

### CODE REVIEW

**Comment by the3dwargamer** [comment]
Hello,

These all show as closed so I cannot incorporate them.  I have tried to add you as a member to the repository so you can make changes to the data files without having to be approved by me but I can’t seem to figure out how to do that.  Is there any type of request to be a member or anything when you access the repository?  This is my first BS data set and I am new to Github.  I have been busy the last week and haven’t had time to review things.

Thanks,

Patrick.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by LeadAddict** [comment]
No worries, the last two pull requests were accidental. I am currently working on a forked copy and it auto-suggests your master when I merge back from a branch. My apologies!

If you want to give me commit permissions on your repo, here's how it works: https://stackoverflow.com/questions/14969281/git-how-to-give-people-push-access-that-needs-to-be-merged-in-by-organizers

Cheers
Jean

**Comment by the3dwargamer** [comment]
So I looked into it more and the “settings tab” that you add collaborators to is not on my screen so I cannot add any permissions.  I believe that is because my repository is just a sub underneath the larger BSDATA repository and they originally set me up as having access but I don’t have the security to add others.  I will keep looking into and maybe ask them to add you as a collaborator if I have to.  For now, if you keep doing pushes I will approve and merge.  I just approved your last push and put out a new revision to the public.  I have not had time to test your changes before pushing the rev, have you been testing it in BS for functionality before doing the push?

Thanks,
Patrick

PS. Are you on Facebook?   Facebook messenger would be a more efficient communication method if so, if not email is fine.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by LeadAddict** [comment]
I have tested these changes locally but as more eyes look at I expect more
data issues to pop up. The data files all do work and load correctly, I
haven't verified point values or profiles (although I already noticed and
corrected a few things).

I will send you my FB details via email, this thread is public.

Cheers

**Pull request closed without merging**
